# 0.7.1 (2023-05-23)

## Bug Fixes

- Исправлена функция `setup_logging`.

  В onETL==0.7.0 вызов `onetl.log.setup_logging()` приводил к ошибке логирования:

  ``` text title="exception message"

  Traceback (most recent call last):
  File "/opt/anaconda/envs/py39/lib/python3.9/logging/__init__.py", line 434, in format
      return self._format(record)
  File "/opt/anaconda/envs/py39/lib/python3.9/logging/__init__.py", line 430, in _format
      return self._fmt % record.dict
  KeyError: 'levelname:8s'
  ```

- Исправлены примеры установки.

  В onETL==0.7.0 приводились примеры установки с применением extras:

  ``` bash title="before"

  pip install onetl[files, kerberos, spark]
  ```

  Однако, это приводило к ошибке pip:

  ``` text title="exception"

  ERROR: Invalid requirement: 'onet[files,'
  ```

  Это происходило из-за наличия пробелов в extras. Исправлено:

  ``` bash title="after"

  pip install onetl[files,kerberos,spark]
  ```
